language: ruby
gemfile:
  - Gemfile

install:
  - bundle install --jobs=3 --retry=3
  
script: bundle exec rspec

deploy:
  provider: rubygems
  api_key: 1d9a1a9ffa6e3ce02d1f3786595edcfe
  gemspec: logstash-output-opentsdb_using_filter_metrics.gemspec